// Acore syntax adapter. The vendored Pkl syntax/scanner retains its Apache-2.0
// license. Domain nodes are syntax only; acore-lsp owns semantic validation.
const pkl = require('./vendor/pkl/grammar');
const commaSep = rule => optional(seq(rule, repeat(seq(',', rule)), optional(',')));

module.exports = grammar(pkl, {
  name: 'acore',
  extras: ($, original) => original.concat(';'),
  conflicts: ($, original) => original.filter(conflict =>
    !conflict.some(rule => rule.name === 'unqualifiedAccessExpr')).concat([
    [$.objectProperty, $.qualifiedIdentifier, $._callName],
    [$.qualifiedIdentifier, $._callName],
    [$.domainBinding, $._callName],
    [$.domainBlock, $._callName],
    [$.typedIdentifier, $._callName],
    [$.objectProperty],
    [$.objectEntry, $.listExpr],
    [$.objectEntry],
    [$.memberPredicate],
    [$.constructorExpr, $.genericExpr],
    [$.domainDeclaration, $.workflowStatement],
    [$.domainBinding, $.routeParameter],
    [$.domainBinding, $.routeParameter, $._callName],
    [$.routeParameter, $._callName],
    [$.routeDeclaration, $._callName],
    [$.namedRouteDeclaration, $._callName],
    [$.methodHeader, $.qualifiedIdentifier],
    [$.domainDeclaration, $._propertyName],
    [$.domainDeclaration, $._callName],
    [$.methodHeader, $.domainDeclaration, $._callName],
    [$.qualifiedIdentifier, $._propertyName, $._callName],
    [$.typedIdentifier, $._propertyName],
    [$.domainBlock, $._propertyName],
    [$._propertyName, $._callName],
  ]),
  rules: {
    module: $ => seq(optional($.shebangComment), optional(choice(
      seq($.profileDeclaration, optional($.moduleHeader)),
      seq($.moduleHeader, optional($.profileDeclaration)))),
      repeat(choice($.importClause, $.importGlobClause,
        $.extendDeclaration, $._moduleMember, $.domainDeclaration,
        $.domainFunction, $.domainBinding, $.domainBlock, $.domainCall,
        $.useContractDeclaration, $.useExtensionDeclaration, $.stylesDeclaration,
        $.migrationDeclaration, $.applicationReference, $.workflowStatement))),
    profileDeclaration: $ => seq('profile', choice($.identifier, alias(choice('backend', 'frontend', 'database', 'package', 'extension'), $.identifier)), optional($.intLiteralExpr)),
    extendDeclaration: $ => seq('extend', choice($.qualifiedIdentifier, $.stringConstant), optional($.objectBody)),
    domainDeclaration: $ => prec.right(seq(optional('override'),
      choice('model', 'endpoint', 'entity', 'projection', 'relationship', 'invariant',
        'variant', 'policy', 'enum', 'app', 'page', 'screen', 'component', 'theme',
        'token', 'stylesheet', 'database', 'schema', 'table', 'unique', 'foreignKey',
        'index', 'check', 'service', 'permission', 'guard', 'operation', 'serverPolicy',
        'interceptor', 'failure', 'serverCache', 'outbound', 'multipart', 'streamPolicy',
        'event', 'publisher', 'consumer', 'job', 'schedule', 'webhook', 'resource',
        'form', 'perform', 'invoke', 'sequence', 'extension', 'collation', 'role',
        'roleGrant', 'grant', 'rowSecurity', 'range', 'domain', 'composite', 'view',
        'materializedView', 'partitionedTable', 'partition', 'function', 'procedure',
        'aggregate', 'trigger', 'foreignDataWrapper', 'foreignServer', 'userMapping',
        'foreignTable', 'evolution', 'referenceData', 'store', 'form_model', 'field',
        'rule', 'async', 'array', 'server'),
      field('name', choice($.qualifiedIdentifier, $.stringConstant)), optional($.argumentList), optional($.typeAnnotation),
      optional($.objectBody), optional(seq('also', $.identifier)))),
    domainFunction: $ => seq(optional('pure'), choice('action', 'fn'),
      field('name', $.identifier), $.parameterList, optional(choice($.typeAnnotation, seq('->', $._type))),
      choice($.objectBody, seq('=', $._expr))),
    domainBinding: $ => prec.right(seq(choice('state', 'derived', 'computed', 'query', 'mutation'), field('name', $.identifier),
      choice(seq(optional($.typeAnnotation), '=', $._expr, optional($.operationClauses)), $.objectBody))),
    operationClauses: $ => prec.right(choice(seq(repeat1(seq(choice('options', 'optimistic'), $.argumentList)), optional(seq('when', $._expr))), seq('when', $._expr))),
    domainBlock: $ => seq(choice('view', 'effect', 'watch', 'batch', 'handle', 'require'), $.objectBody),
    domainCall: $ => seq($.qualifiedIdentifier, $.argumentList),
    routeDeclaration: $ => seq('route', $.stringConstant, '=>', $._expr),
    namedRouteDeclaration: $ => prec.right(seq('route', field('name', $.identifier), $.stringConstant,
      '=>', field('page', $.qualifiedIdentifier), optional($.objectBody))),
    migrationDeclaration: $ => seq('migration', field('version', $.intLiteralExpr), $.parameterList, '=', $._expr),
    routeParameter: $ => seq(choice('path', 'query'), field('name', $.identifier), $.typeAnnotation, optional(seq('=', $._expr))),
    applicationReference: $ => seq(choice('layout', 'denied', 'redirect', 'not_found', 'signed_out'), choice($.qualifiedIdentifier, $.stringConstant)),
    workflowStatement: $ => seq(choice('go', 'replace', 'form', 'store', 'session', 'emit'),
      field('command', $.qualifiedIdentifier), optional($.argumentList)),
    updateStatement: $ => seq('update', field('target', $.qualifiedAccessExpr), '=', $._expr),
    _objectMember: ($, original) => choice(original, $.domainDeclaration,
      $.domainFunction, $.domainBinding, $.domainBlock, $.routeDeclaration, $.namedRouteDeclaration,
      $.routeParameter, $.applicationReference, $.migrationDeclaration, $.workflowStatement,
      $.updateStatement, $.domainIf, $.assignmentStatement),
    useContractDeclaration: $ => seq('use', 'contract', $.identifier, 'from', $.stringConstant,
      optional(seq('audience', $.stringConstant))),
    useExtensionDeclaration: $ => seq('use', 'extension', $.identifier, 'from', $.stringConstant,
      optional(seq('export', $.stringConstant))),
    assignmentStatement: $ => seq(field('target', $.qualifiedAccessExpr), '=', $._expr),
    domainIf: $ => prec.right(seq('if', $._expr, $.objectBody, optional(seq('else', choice($.objectBody, $.domainIf))))),
    objectBodyParameters: $ => seq($._parameter, repeat(seq(',', $._parameter)), choice('->', '=>')),
    objectProperty: $ => seq(repeat($.modifier), $._propertyName, choice($.typeAnnotation,
      seq(optional($.typeAnnotation), '=', $._expr), repeat1($.objectBody))),
    argumentList: $ => seq(alias($._open_argument_paren, '('), commaSep(choice($.namedArgument, $._expr)), ')'),
    namedArgument: $ => seq(field('name', $._fieldName), ':', field('value', $._expr)),
    _propertyName: $ => choice($.identifier, alias(choice('theme', 'token', 'store', 'form',
      'field', 'rule', 'async', 'array', 'server', 'view', 'route', 'path', 'query',
      'role', 'range', 'domain', 'schema', 'table', 'action', 'event', 'model',
      'entity', 'projection', 'policy', 'guard', 'state'), $.identifier)),
    _fieldName: $ => choice($.identifier, alias(choice('class', 'module', 'function',
      'new', 'if', 'else', 'import', 'read', 'for', 'in', 'const', 'fixed', 'local',
      'hidden', 'this', 'super', 'true', 'false', 'null', 'unknown', 'nothing', 'out', 'outer', 'theme', 'token', 'store', 'form',
      'field', 'rule', 'async', 'array', 'server', 'view', 'route', 'path', 'query',
      'role', 'range', 'domain', 'schema', 'table', 'function', 'action', 'event',
      'model', 'entity', 'projection', 'policy', 'guard', 'state', 'value'), $.identifier)),
    _callName: $ => choice($.identifier, alias(choice('require', 'handle', 'query', 'mutation',
      'invoke', 'perform', 'function', 'field', 'rule', 'async', 'array', 'server', 'path', 'route'), $.identifier)),
    unqualifiedAccessExpr: $ => seq($._callName, optional(seq(optional($.methodTypeArguments), $.argumentList))),
    qualifiedAccessExpr: $ => prec.left(22, seq(field('receiver', $._expr), choice('.', '?.'),
      $._fieldName, optional(seq(optional($.methodTypeArguments), $.argumentList)))),
    constrainedType: $ => prec.right(30, seq($._type, alias($._open_argument_paren, '('),
      commaSep(choice($.namedArgument, $._expr)), ')')),
    _expr: ($, original) => choice(original, $.listExpr, $.implicitMemberExpr,
      $.constructorExpr, $.genericExpr, $.objectLiteralExpr, $.pipeLambdaExpr, $.unitLiteralExpr),
    unitLiteralExpr: $ => token(seq(/[0-9][0-9_]*/, optional(seq('.', /[0-9][0-9_]*/)),
      choice('ns', 'us', 'ms', 's', 'm', 'h', 'd', 'b', 'kb', 'mb', 'gb', 'kib', 'mib', 'gib'))),
    listExpr: $ => seq('[', commaSep($._expr), ']'),
    implicitMemberExpr: $ => seq('.', $.identifier),
    constructorExpr: $ => prec(23, seq($.qualifiedIdentifier, optional($.typeArgumentList),
      optional($.argumentList), $.objectBody)),
    genericExpr: $ => prec(23, seq($.qualifiedIdentifier, $.typeArgumentList)),
    objectLiteralExpr: $ => seq('{', commaSep($.objectLiteralEntry), '}'),
    objectLiteralEntry: $ => seq(choice($._fieldName, $.stringConstant), ':', $._expr),
    pipeLambdaExpr: $ => prec(-11, seq('|', commaSep($.typedIdentifier), '|', $._expr)),
    stylesDeclaration: $ => seq('styles', $.styleBody),
    styleBody: $ => seq('{', optional($.styleContent), '}'),
    styleContent: $ => repeat1(choice($.styleText, $.styleString, $.styleBody)),
    styleText: $ => token(/[^{}"']+/),
    styleString: $ => token(choice(/"([^"\\]|\\.)*"/, /'([^'\\]|\\.)*'/)),
  },
});
